services:
  # --- Banco de Dados Relacional (Persistência Principal) ---
  postgres-db:
    image: postgres:16-alpine
    container_name: votacao-db
    environment:
      - POSTGRES_DB=votacao_db
      - POSTGRES_USER=app_votacao
      - POSTGRES_PASSWORD=senha_desafio_local
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_votacao -d votacao_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - votacao-network

  # --- Banco de Dados em Memória (Cache & Locks) ---
  redis:
    image: redis:7-alpine
    container_name: votacao-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - votacao-network

  # --- Mensageria (Coordenação) ---
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: votacao-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - votacao-network

  # --- Mensageria (Broker) ---
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: votacao-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - votacao-network

volumes:
  postgres_data:
  redis_data:

networks:
  votacao-network:
    driver: bridge