spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/votacao_db
    username: app_votacao
    password: senha_desafio_local
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true